import 'package:iti_23_g2/const.dart';

List<Map<String, dynamic>> messangerJson = [
  {
    "name": "Ahmed",
    "message": "Hello",
    "icon": "received",
    "image": avatarImage,
  },
  {
    "name": "Moamed",
    "message": "Welcome",
    "image": avatarImage2,
    "icon": "read",
  },
  {
    "name": "Osama",
    "message": "Yes",
    "createdAt": "11:49 PM",
    "image": avatarImage,
    "messageType": "gif",
    "icon": "unread",
  },
  {
    "name": "Es",
    "message": "No",
    "createdAt": "11:49 PM",
    "image": avatarImage2,
    "messageType": "gif",
    "icon": "unread",
  },
  {
    "name": "OS",
    "message": "Hello",
    "createdAt": "11:49 PM",
    "image": avatarImage,
    "messageType": "gif",
    "icon": "unread",
  },
  {
    "name": "IH",
    "message": "Hello",
    "createdAt": "11:49 PM",
    "image": avatarImage2,
    "messageType": "video",
    "icon": "unread",
  },
  {
    "name": "Ahmed",
    "message": "Hello",
    "createdAt": "11:49 PM",
    "image": avatarImage,
    "messageType": "video",
    "icon": "read",
  },
  {
    "name": "Moamed",
    "message": "Welcome",
    "createdAt": "11:49 PM",
    "image": avatarImage2,
    "messageType": "video",
    "icon": "unread",
  },
  {
    "name": "Osama",
    "message": "Yes",
    "createdAt": "11:49 PM",
    "image": avatarImage,
    "messageType": "video",
    "icon": "unread",
  },
  {
    "name": "Es",
    "message": "No",
    "createdAt": "11:49 PM",
    "image": avatarImage2,
    "messageType": "video",
    "icon": "unread",
  },
  {
    "name": "OS",
    "message": "Hello",
    "createdAt": "11:49 PM",
    "image": avatarImage,
    "messageType": "video",
    "icon": "unread",
  },
  {
    "name": "IH",
    "message": "Hello",
    "createdAt": "11:49 PM",
    "image": avatarImage2,
    "messageType": "video",
    "icon": "read"
  },
];
